<?php
/**
 * Init Gallery Slider
 */
?>

<script type="text/x-magento-init">
{
    ".gallery__wrapper": {
        "elogicSlider":{
            "selector":".gallery__slider ul",
            "sliderOptions":{
                "slidesToShow": 3,
                "centerMode": true,
                "arrows": true,
                "dots":true,
                "responsive": [
                    {
                        "breakpoint": 992,
                        "settings": {
                            "slidesToShow": 2
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }

    }
    }

    

</script>



<?php
/**
 * --------------------------------
 */


?>

