<?php
/**
 * Init Sidebar Slider
 */
?>

<script type="text/x-magento-init">
    {
    ".sidebar-main": {
        "elogicSlider": {
            "selector":".catalog__sidebar__baners",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>

<?php
/**
 * Init Select for sorter
 */
?>

<script type="text/x-magento-init">
    {
    ".toolbar-sorter": {
        "elogicSelect": {
            "selector":"#sorter",
            "sliderOptions":{}
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>

<?php
/**
 * Init Select for limiter options
 */
?>

<script type="text/x-magento-init">
    {
    ".field.limiter": {
        "elogicSelect": {
            "selector":".control #limiter",
            "sliderOptions":{}
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>
