<?php
/**
 * Init Banner Slider
 */
?>

<script type="text/x-magento-init">
    {
    ".sidebar-main": {
        "elogicSlider": {
            "selector":".catalog__sidebar__baners",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>