<?php
/**
 * Init Banner Slider
 */
?>

<script type="text/x-magento-init">
    {
    ".banner__wrapper": {
        "elogicSlider": {
            "selector":".banner__items",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "infinite": false,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>

<?php
/**
 * Init Our products Slider
 */
?>

<script type="text/x-magento-init">
{
    "#our_catalog__list": {
        "elogicSlider": {
            "selector":"#our_catalog__list .product-items",
            "sliderOptions":{
                "slidesToShow": 4,
                "slidesToScroll": 4,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 3,
                            "slidesToScroll": 3
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
}
</script>

<?php
/**
 * --------------------------------
 */
?>

<?php
/**
 * Init Group Products Slider
 */
?>

<script type="text/x-magento-init">
    {
    "#group__product": {
        "elogicSlider": {
            "selector":".group_product__item .product-items",
            "sliderOptions":{
                "dots": false,
                "arrows": true,
                "rows": 3,
                "slidesToShow": 1,
		        "slidesToScroll": 1
            }
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>

<?php
/**
 * Init News&Blog Slider
 */
?>

<script type="text/x-magento-init">
    {
    ".news_blog__wrap": {
        "elogicSlider": {
            "selector":".news_blog__items",
            "sliderOptions":{
                "slidesToShow": 3,
                "slidesToScroll": 3,
                "responsive": [
                    {
                        "breakpoint": 992,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>

<?php
/**
 * Init Brands Slider
 */
?>

<script type="text/x-magento-init">
    {
    ".shop_by_brands": {
        "elogicSlider": {
            "selector":".shop_by_brands__items",
            "sliderOptions":{
                "slidesToShow": 5,
                "slidesToScroll": 5,
                "centerMode": true,
                "dots": true,
                "autoplay": true,
                "responsive": [
                    {
                        "breakpoint": 992,
                        "settings": {
                            "slidesToShow": 4
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 3
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>

<?php
/**
 * --------------------------------
 */
?>